### ISSUE TITLE
How can I train my own data set? What do I need to prepare?

### ISSUE THREAD

**Issue by Mikcal** [knorth55/chainer-light-head-rcnn#3]
I want to use this to train my own data, I try to train on zengarden code, but I find myself unable to test.  So I want to try it with your model, can I use it to train my own data? And how to do it.
thanks

**Comment by knorth55** [comment]
First, you need to write Dataset class as https://github.com/chainer/chainercv/blob/master/chainercv/datasets/coco/coco_bbox_dataset.py.
If you want to do just inference, please modify `examles/eval_coco.py` to load your dataset class and hyper parameters.
If you want to train new model, please modify `examples/train_multi.py`.
