### ISSUE TITLE
 Light head rcnn with other  feature extractor 

### ISSUE THREAD

**Issue by aggpankaj2** [knorth55/chainer-light-head-rcnn#5]
Hi @knorth55  
what changes we need to do for Light head rcnn with other feature extractor ( exception or mobilenetV2)

**Comment by knorth55** [comment]
You can change extractor written here.

https://github.com/knorth55/chainer-light-head-rcnn/blob/master/light_head_rcnn/links/model/light_head_rcnn_resnet101.py#L136-L160
