### ISSUE TITLE
Add to ChainerCV

### ISSUE THREAD

**Issue by 23pointsNorth** [knorth55/chainer-light-head-rcnn#6]
Hi @knorth55 ,

Thanks for the implementation! I saw that it's under MIT licence and was wondering if you were thinking of adding it to the ChainerCV repo? 

I think it would be a useful contribution. 

Thanks,
Daniel

**Comment by 23pointsNorth** [comment]
If you need any help, give me a shout :)

**Comment by knorth55** [comment]
`v0.12` will be released in a week, I'm targeting to `v0.13`
