### ISSUE TITLE
How to prepare dataset for training?

### ISSUE THREAD

**Issue by mmaaz60** [knorth55/chainer-light-head-rcnn#9]
Hi @knorth55,

How can I prepare the COCO dataset for training and validation? Are there any instructions out there? Thanks

**Comment by knorth55** [comment]
@mmaaz60 Hi,
as https://github.com/knorth55/chainer-light-head-rcnn/blob/master/examples/train_multi.py#L20,
we use chainercv https://github.com/chainer/chainercv for coco dataset preparation,
and the coco dataset will be downloaded automatically.
please try it.

**Comment by mmaaz60** [comment]
Thanks @knorth55
